# version: '3.9'
services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./database/mongo:/data/db
      - ./database/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

  fastapi:
    build:
      context: ./
      dockerfile: fastapi.dockerfile
    container_name: fastapi
    volumes:
      - './malaria_backend/fastapi:/app'
    ports:
      - 8000:8000
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      PYTHONPATH: /app

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: react.dockerfile
    volumes:
      - './frontend:/app'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true # make the apps interactive